
# all: booterTest lightEventReciver topicDistributerTest
all: booterTest 
test: booterTest

# booterTest lightEventReciver topicDistributerTest:
booterTest:
	@$(MAKE) -C $@ test

.PHONY: booterTest lightEventReciver topicDistributerTest

