
# all: booterTest lightEventReciver topicDistributerTest
all: soboot  
test: soboot 

# booterTest lightEventReciver topicDistributerTest:
soboot:
	@$(MAKE) -C $@ test

.PHONY: sobooter booterTest lightEventReciver topicDistributerTest

