
# all: booterTest lightEventReciver topicDistributerTest
all: sobooter  
test: sobooter 

# booterTest lightEventReciver topicDistributerTest:
booterTest:
	@$(MAKE) -C $@ test

.PHONY: sobooter booterTest lightEventReciver topicDistributerTest

